# -*- coding: utf-8 -*-
"""img2img_connect.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14KhA1KWXKmTPBkEXGzqfrkvh2OUmnX2-
"""

from diffusers import StableDiffusionImg2ImgPipeline
import requests
import torch
import os
from PIL import Image
from io import BytesIO


def generate_img2img(prompt, model_directory, init_image_path, steps=50, scale=8, save_path=None):

    # Load the Stable Diffusion pipeline
    pipe = StableDiffusionImg2ImgPipeline.from_pretrained("stable-diffusion-v1-5/stable-diffusion-v1-5", torch_dtype=torch.float16)
    pipe.unet.load_attn_procs('/content/drive/MyDrive/sd_model_fintuning_LoRA/fintune_model2/checkpoint-190000/pytorch_lora_weights_oil.safetensors')
    pipe.to("cuda")

    # Fixed negative prompt
    neg_prompt = '''FastNegativeV2, (bad-artist:1.0), (loli:1.2),
    (worst quality, low quality:1.4), (bad_prompt_version2:0.8),
    bad-hands-5, lowres, bad anatomy, bad hands, ((text)), (watermark),
    error, missing fingers, extra digit, fewer digits, cropped,
    worst quality, low quality, normal quality, ((username)), blurry,
    (extra limbs), bad-artist-anime, badhandv4, EasyNegative,
    ng_deepnegative_v1_75t, verybadimagenegative_v1.3, BadDream,
    (three hands:1.1), (three legs:1.1), (more than two hands:1.4),
    (more than two legs,:1.2), badhandv4, EasyNegative, ng_deepnegative_v1_75t,
    verybadimagenegative_v1.3, (worst quality, low quality:1.4), text, words, logo, watermark'''

    init_image = Image.open(init_image_path).convert("RGB")
    init_image = init_image.resize((512, 512))


    # Generate the image
    image = pipe(prompt, negative_prompt=neg_prompt,image=init_image,
                 num_inference_steps=steps, guidance_scale=scale).images[0]

    # # Save the image if a save path is provided
    # if save_path:
    #     image.save(save_path)
    #     print(f"Image saved at: {save_path}")

    return image

# # Example usage

# # # 아래 프롬프트는 LLM에서 받아와야함

# # # positive prompt
# prompt = ''' (masterpiece, best quality),
# ((impressionism, oil painting with brushstrokes, oil painting)) ,
# family eating pizza together at a home table, 1gril , mom and dad, upper body, focus on face
# smile, highly detailed facial expressions, joyful atmosphere, warm and soft lighting, hartwarming moments,
# relaxed and happy atmosphere '''


# image = generate_img2img(prompt,model_directory='가중치 경로', init_image_path='이미지 로')
# # #, save_path="저장 경로")
# image